steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -f
    - ./traducteur-audio/Dockerfile
    - -t
    - gcr.io/$PROJECT_ID/traducteur-universel
    - .
images:
- gcr.io/$PROJECT_ID/traducteur-universel



