
services:
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.runCommand('ping').ok\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  flask:
    build:
      context: ./traducteur-audio
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ""
        HTTPS_PROXY: ""
        NO_PROXY: "localhost,127.0.0.1,http.docker.internal,registry-1.docker.io"
    ports:
      - "5000:5000"
    volumes:
      - ./public:/app/public
      - ./traducteur-audio/models:/app/models
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    environment:
      FLASK_ENV: development

volumes:
  mongo-data:

